services:

  nginx:
    image: nginx:alpine
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/
    ports:
      - "80:80"
    networks:
      - web
    depends_on:
      - php

  php:
    build:
      dockerfile: .docker/php/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=localhost
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./:/var/www/
    networks:
      - web

  mysql:
    image: mysql:8.3
    ports:
      - "3306:3306"
    volumes:
      - mysql_database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      TZ: Europe/Moscow
    networks:
      - web

  pgsql:
    image: postgres:16.2
    ports:
        - "5432:5432"
    volumes:
        - pgsql_database:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}

networks:
  web:
    driver: bridge

volumes:
  mysql_database:
    driver: local
  pgsql_database:
      driver: local
